version: '3.8'
services:
  nest-api:
    container_name: nest-api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./:/app/
      - /app/node_modules
    restart: always
    networks:
      - my_network.
  postgres:
    build: ./db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      - my_network
      
networks:
  my_network:
    driver: bridge